[[react-and-spring-data-rest-part-2]]
= React.js and Spring Data REST: Part 2 - Hypermedia Controls
:prev_session: https://github.com/gregturn/react-and-spring-data-rest/tree/master/basic

In the {prev_session}[previous session], you found out how to stand up a backend payroll service to store employee data using Spring Data REST. A key feature it lacked was using the hypermedia controls provided by Spring Data REST.

== Step 0 - Setting up your environment

To get off the ground, you can either grab the code from this repository, or you can do it yourself, by hand. This project is based on the previous session with more modifications coming.


== ...and then there was REST

[quote, Roy T. Fielding, http://roy.gbiv.com/untangled/2008/rest-apis-must-be-hypertext-driven]
I am getting frustrated by the number of people calling any HTTP-based interface a REST API. Today’s example is the SocialSite REST API. That is RPC. It screams RPC....What needs to be done to make the REST architectural style clear on the notion that hypertext is a constraint? In other words, if the engine of application state (and hence the API) is not being driven by hypertext, then it cannot be RESTful and cannot be a REST API. Period. Is there some broken manual somewhere that needs to be fixed?

So, what exactly ARE hypermedia controls, i.e. hypertext, and how can you use them? To find out, let's take a step back and look at the core mission of REST.

The core concept of REST was to borrow some of the ideas that made the web so successful and apply them to APIs. Despite the web's vast size, dynamic nature, and low rate that clients, i.e. browsers, have to updated, the web is an amazing success. Roy Fielding sought to use some of its constraints and features and see if that would afford similar expansion of API production and consumption.

One of the constraints are to limit the number of verbs. For REST, the primary ones are GET, POST, PUT, DELETE, and PATCH. There are others, but we won't get into them here.

* GET - fetch the state of a resource without altering the system
* POST - create a new resource without saying where
* PUT - replace an existing resource, overwriting whatever else is already there (if anything)
* PATCH - alter an existing resource partially

NOTE: There is debate about the exact semantics of *PATH* due it not being part of the HTTP spec where these other verbs are defined. Spring Data REST does the following: PUT overrides an existing resource, nulling out unspecified attributes. PATCH partially updates an existing resource, ignoring unspecified attributes. A good way to remember this is "what you PUT is what you GET."

WARNING: Spring Data REST supports Spring Data Cassandra because it embraces the repository programming model. But Cassandra itself doesn't support upseting null into fields. Hence, Spring Data REST and PUT/PATCH doesn't abide by these assumptions when working with Cassandra.

Another feature of REST is to include links to relevant resources. For example, if you were looking at an order, a RESTful API would include a link to the related customer, links to the catalog of items, and perhaps a link to the store from which the order was placed.

== Turning on paging from the backend

Before we get underway with using frontend hypermedia controls, let's turn on all the controls we can. Spring Data REST provides paging support. To use it, you just need to tweak the repository definition.

.src/main/java/com/greglturnquist/payroll/EmployeeRepository.java
[source,java]
----
include::src/main/java/com/greglturnquist/payroll/EmployeeRepository.java[tag=code]
----

Your interface now extends `PagingAndSortingRepository` which adds extra options to set page size, and also adds navigational links to hop from page to page. The rest of the backend is the same (exception for some https://github.com/gregturn/react-and-spring-data-rest/blob/master/hypermedia/src/main/java/com/greglturnquist/payroll/DatabaseLoader.java[extra pre-loaded data] to make things interesting).

Restart the application (`mvn spring-boot:run`) and you can see how it works.

----
$ curl localhost:8080/api/employees?size=2
{
  "_links" : {
    "first" : {
      "href" : "http://localhost:8080/api/employees?page=0&size=2"
    },
    "self" : {
      "href" : "http://localhost:8080/api/employees"
    },
    "next" : {
      "href" : "http://localhost:8080/api/employees?page=1&size=2"
    },
    "last" : {
      "href" : "http://localhost:8080/api/employees?page=2&size=2"
    }
  },
  "_embedded" : {
    "employees" : [ {
      "firstName" : "Frodo",
      "lastName" : "Baggins",
      "description" : "ring bearer",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/api/employees/1"
        }
      }
    }, {
      "firstName" : "Bilbo",
      "lastName" : "Baggins",
      "description" : "burglar",
      "_links" : {
        "self" : {
          "href" : "http://localhost:8080/api/employees/2"
        }
      }
    } ]
  },
  "page" : {
    "size" : 2,
    "totalElements" : 6,
    "totalPages" : 3,
    "number" : 0
  }
}
----

The default page size is 20, so to see how it works, this shows it with `?size=2` applied. As expected, only two employees are listed. In addition, there is also a *first*, *next*, and *last* link.

If you navigate to the *next* link, you'll then see a *prev* link as well:

----
$ curl "http://localhost:8080/api/employees?page=1&size=2"
{
  "_links" : {
    "first" : {
      "href" : "http://localhost:8080/api/employees?page=0&size=2"
    },
    "prev" : {
      "href" : "http://localhost:8080/api/employees?page=0&size=2"
    },
    "self" : {
      "href" : "http://localhost:8080/api/employees"
    },
    "next" : {
      "href" : "http://localhost:8080/api/employees?page=2&size=2"
    },
    "last" : {
      "href" : "http://localhost:8080/api/employees?page=2&size=2"
    }
  },
...
----

NOTE: When using "&" in URL query parameters, the command line things it's a line break. Wrap the whole URL with quotation marks to bypass that.

That looks neat, but it will be even better when you update the frontend to take advantage of that.

== Navigating by relationship

Since there are no more modifications needed on the backend, you can focus purely on the frontend. (That's part of the beauty of Spring Data REST. No messy controller updates!)

In the previous session, you hardcoded the path to `/api/employees`. Instead, the ONLY path you should hardcode is the root.

[source,javascript]
----
...
var root = '/api';
...
----

With a handy little https://github.com/gregturn/react-and-spring-data-rest/blob/master/hypermedia/src/main/resources/static/follow.js[`follow()` function], you can now start from the root and navigate to where you need!

[source,javascript,indent=0]
----
include::src/main/resources/static/app.jsx[tag=follow-1]
----

In the previous session, the loading was done directly inside `componentDidMount()`. In this session, we are making it possible to reload the entire list of employees when the page size is updated. To do so, we have moved things into `loadFromServer()`.

[source,javascript,indent=0]
----
include::src/main/resources/static/app.jsx[tag=follow-2]
----

`loadFromServer` is very similar the previous session, but instead if uses `follow()`.

* The first argument is the `client` object used to make REST calls.
* The second argument is the root URI to start from.
* The third argument is an array of relationships to navigate along. Each one can be a string or an object.

The array of relationships can be as simple as `["employees"]`, meaning when the first call is made, look in *_links_ for the relationship (or *rel*) named *employees*. Find its *href* and navigate to it. If there is another relationship in the array, rinse and repeat.

Sometimes, just a rel isn't enough. In this fragment of code, it is also plugging in a query parameter of *?size=<pageSize>*. There are other options that can be supplied, as you'll see further along.

== Grabbing JSON Schema metadata

After navigating to *employees* with the size-based query, the *employeeCollection* is processed. In the previous session, we called it day. In this situation, we are grabbing some extra metadata, http://json-schema.org/[JSON Schema] found a `/api/employees/schema`.

You can see the data yourself:

----
$ curl http://localhost:8080/api/employees/schema
{
  "title" : "com.greglturnquist.payroll.Employee",
  "properties" : {
    "firstName" : {
      "readOnly" : false,
      "type" : "string"
    },
    "lastName" : {
      "readOnly" : false,
      "type" : "string"
    },
    "description" : {
      "readOnly" : false,
      "type" : "string"
    }
  },
  "descriptors" : { },
  "type" : "object",
  "$schema" : "http://json-schema.org/draft-04/schema#"
}
----

NOTE: Navigating to the JSON Schema metadata requires hand editing the URI. There are plans underway to add a navigable link in the future to Spring Data REST to best use hypermedia concepts.

By capturing this information in the container's state, you can make good use of it later on when building data forms.

[[creating-new-records]]
== Creating new records

Equipped with all this metadata, you can now add some extra controls to the UI. To do so, you can create a new React component, `<CreateDialog />`.

[source,javascript,indent=0]
----
include::src/main/resources/static/app.jsx[tag=create-dialog]
----

This new component has the expected `render()` function. At the top of this function is call to map over the supplied JSON Schema attribute data, and convert them into an array of `<input>` elements.

* *key* is again needed by React to distinguish between multiple child nodes.
* It's a simple text-based entry field.
* *placeholder* is where we can show the user with field is which.
* You may used to having a *name* attribute, but it's not necessary. With React, *ref* is the mechanism to grab a particular DOM node (as you'll soon see).


Inside this component's top-level `<div>` is an anchor tag and another `<div>`. The anchor tag is the button to open the dialog. And the nested `<div>` is the hidden dialog itself. In this example, we are use pure HTML5 and CSS3. No JavaScript at all! You can https://github.com/gregturn/react-and-spring-data-rest/blob/master/hypermedia/src/main/resources/static/main.css[see the CSS code] used to show/hide the dialog. We won't dive into that here.

Nestled inside `<div id="createEmployee">` is a form. Inside the form is where the dynamic list of input fields get injected followed by the *Create* button. The button has an `onClick={this.handleSubmit}` event handler. This is the React way of registering an event handler.

If you look at the `handleSubmit()` function, it starts off by stopping the standard event from bubbling further up the hierarchy. It then uses the same JSON Schema attribute properties to iterate over and find each `<input>` using `React.findDOMNode(self.refs[attribute])`.

`self.refs` is a way to reach out and grab a particular React component by name. In that sense, you are ONLY getting the virtual DOM component. To grab the actual DOM element (in this case to read its value), you then plug it into `React.findDOMNode()`.

After iterating over every attribute and building up the `newEmployee` object, we invoke a callback to `onCreate()` the new employee. Tracing the `onCreate` function back to the top at `App.onCreate`, you can see how it operates.

[source,javascript,indent=0]
----
include::src/main/resources/static/app.jsx[tag=create]
----

Once again, you use the `follow()` function to navigate to the *employees* resource where POST operations are performed. In this case, there was no need to apply any parameters, so the string-version of rels is fine. In this situation, the POST call is returned. This allows the next `then()` clause handle processing the outcome of the POST.

New records are typically added to end of the dataset. Since you are looking at certain page size, it's logcical to expect the new employee record to not be on the current page. To handle this, you need to fetch a new batch of data with the same page size applied. Again, that promise is returned for the final clause inside `done()`.

Since the user probably wants to see the newly created employee, you can then use the hypermedia controls and navigate to the *last* entry.

This introduces the concept of paging in our UI. Let's tackle that next!

[[NOTE]]
====
First time using a promise-based API? https://promisesaplus.com/[Promises] are a way to kick of asynchronous operations and then register a function to respond when the task is done. Promises are designed to be chained together to avoid "callback hell". Look at the following flow.

[source,javascript]
----
when.promise(async_func_call())
	.then(function(results) {
		/* process the outcome of async_func_call */
	})
	.then(function(more_results) {
		/* process the previous then() return value */
	})
	.done(function(yet_more) {
		/* process the previous then() and then wrap things up */
	});
----

For more details, check out http://know.cujojs.com/tutorials/promises/consuming-promises[this tutorial on promises].

The secret thing to remember with promises is that `then()` functions NEED to return something, whether its a value or another promise.  `done()` functions do NOT need to return anything, and you don't chain anything after one. In case you haven't noticed yet, `client` (which is an instance of `rest` from rest.js) as well as the `follow` function return promises.
====

IMPORTANT: React operates with a one-way data flow. The idea is to have state at the top and let it flow downward into relevant components. Instead of a lower level component push state changes up to a higher level, it is highly recommended you pass in a callback. This might feel new and awkward, but after you spend a few days working with React, you will come to appreciate how this nicely keeps components decoupled.

== Paging through data

You set up paging on the backend and are taking advantage of it when creating new employees.

In <<creating-new-records,the previous section>>, you used the page controls to jump to the *last* page. It would be really handy to dynamically apply it to the UI and let the user navigate as desired. Additionally, flexibly adjusting the controls based on available navigation links would be great.

First, let's check out the `onNavigate()` function you used.

[source,javascript,indent=0]
----
include::src/main/resources/static/app.jsx[tag=navigate]
----

This is defined at the top, inside `App.onNavigate`. Again, this is to allow managing the state of the UI in the top component. After passing `onNavigate()` down to the `<EmployeeList />` React component, the following handlers are coded up to handle clicking on some buttons:

[source,javascript,indent=0]
----
include::src/main/resources/static/app.jsx[tag=handle-nav]
----

Each of these functions intercepts the default event and stops it from bubbling up. Then it invokes the `onNavigate()` function with the proper hypermedia link. 

Finally, you can conditionally display the controls based on which links appear in the hypermedia links in `EmployeeList.render`:

[source,javascript,indent=0]
----
include::src/main/resources/static/app.jsx[tag=employee-list-render]
----

As in the previous session, it still transforms `this.props.employees` into an array of `<Element />` components. Then it builds up an array of `navLinks`, an array of HTML buttons.

NOTE: Because React is based on XML, you can't put "<" inside the `<button>` element. You must instead use the encoded version.

Then you can see `{navLinks}` inserted towards the bottom of the returned HTML.

== Deleting existing records

Deleting entries is much easier. All you need is to get a hold of its HAL-based record, and you can apply *DELETE* to its *self* link.

[source,javascript,indent=0]
----
include::src/main/resources/static/app.jsx[tag=employee]
----

This updated version of the Employee component shows an extra entry at the end of the row, a delete button. It is registered to invoke `this.handleDelete` when clicked upon. The `handleDelete()` function can then invoke the callback passed down while supplying the contextually important `this.props.employee` record.

IMPORTANT: Once again, it's easiest to manage state in the top component, in one place. This might not ALWAYS be the case, but in my own discovery of React, it has become very simple to manage it in one place. By invoking the callback with component-specific details (`this.props.onDelete(this.props.employee)`) it is very easy to orchestrate behavior between components. 

Tracing the `onDelete()` function back to the top at `App.onDelete`, you can see how it operates:

[source,javascript,indent=0]
----
include::src/main/resources/static/app.jsx[tag=delete]
----

The behavior to apply after deleting a record with a page-based UI is a bit tricky. In this case, it reloads the whole data from the server, applying the same page size. Then it shows the first page.

If you are deleting the last record on the last page, it will jump to the first page.

== Adjusting the page size

One way to see how hypermedia really shines is to update the page size. Spring Data REST fluidly updates the navigational links based on the page size.

There is an HTML element at the top of `ElementList.render`: `<input ref="pageSize" defaultValue={this.props.pageSize} onInput={this.handleInput}/>`.

The `ElementList.handleInput` is shown below:

[source,javascript,indent=0]
----
include::src/main/resources/static/app.jsx[tag=handle-page-size-updates]
----

Again, it stops the event from bubbling up. Then it uses the *ref* attribute of the `<input>` to find the DOM node and extract its value, all through React's `findDOMNode()` helper function. Finally, it tests if the input is really a number by checking if its a string of digits. If so, it invokes the callback, sending the new page size to the `App` React component. If not, the last character entered is stripped off and reassigned to the `<input>` element's value.

What does `App` do when it gets a `updatePageSize()`? Check it out:

[source,javascript,indent=0]
----
include::src/main/resources/static/app.jsx[tag=update-page-size]
----

Because a new page size causes changes to all the navigation links, its best to refetch the data and start from the beginning. 

== Review

In this session:

* You turned on Spring Data REST's paging feature.
* You threw out hardcoded URI paths and started using the root URI combined with relationship names or "rels". 
* You updated the UI to dynamically using the page-based hypermedia controls.
* You added the ability to create and delete employees and then update the UI as needed.
* You made it possible to change the page size and have the UI dynamically respond.

Issues?

While the web page is now very dynamic, try opening another browser and point it at the same app. Changes in one browser won't update anything in the other.

That is something we can address in the next session. Until then, happy coding!

